---
title: "Motion chart"
author: "Albert Cobos"
date: "15 de diciembre de 2017"
output: 
    html_document:
        self_contained: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message=FALSE)
```

## An example of what can be done with R

R has very good graphic capabilities. There are lots of packages aimed at producing good graphics. Some examples follow.

## Publication graphics

Adding p-vaues to graphics.


## Maps


## Interactive graphics

This is an example of interactive data visualization with package googleVis.

```{r results='asis'}
library(gapminder)
d <- gapminder

library(googleVis)
suppressPackageStartupMessages(library(googleVis))

# createe motion chart
mc <- gvisMotionChart(d, idvar="country", 
                         timevar="year", 
                         colorvar ="continent", 
                         xvar = "gdpPercap",
                         yvar = "lifeExp", 
                         sizevar="pop",
                         chartid="GapminderData1")
# plot(chart)
plot(mc, tag='chart')

```

## R graph gallery
